import os
from dotenv import load_dotenv


load_dotenv()

TOKEN = os.getenv("BOT_TOKEN", "8415484392:AAHIbb-X0dzxMCdyczmL-FQ8aBBCOOGlSAk")

WAITING_LOCATION = 0
ASKING_LOCATION = 1
CONFIRMING_BUILDING = 2
REGISTRATION_CHOICE = 3
REGISTER_GROUP = 4
REGISTER_AGE = 5
REGISTER_DIRECTION = 6
REGISTER_NAME = 7
MAIN_MENU = 8
SETTINGS = 9
MANUAL_BUILDING_SELECTION = 10

DB_PATH = "KGTU.db"
